//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenPowerCfg.Resources{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PowerManagementResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerManagementResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication1.PowerManagementResource", typeof(PowerManagementResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Argument powerSchemeTitle cannot be null. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullMessage {
            get {
                return ResourceManager.GetString("ArgumentNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        internal static string ChoiceAutomatic {
            get {
                return ResourceManager.GetString("ChoiceAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string ChoiceDisabled {
            get {
                return ResourceManager.GetString("ChoiceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do Nothing 的本地化字符串。
        /// </summary>
        internal static string ChoiceDoNothing {
            get {
                return ResourceManager.GetString("ChoiceDoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        internal static string ChoiceEnabled {
            get {
                return ResourceManager.GetString("ChoiceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low Power Saving 的本地化字符串。
        /// </summary>
        internal static string ChoiceLowPowerSaving {
            get {
                return ResourceManager.GetString("ChoiceLowPowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Performance 的本地化字符串。
        /// </summary>
        internal static string ChoiceMaximumPerformance {
            get {
                return ResourceManager.GetString("ChoiceMaximumPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Power Saving 的本地化字符串。
        /// </summary>
        internal static string ChoiceMaximumPowerSaving {
            get {
                return ResourceManager.GetString("ChoiceMaximumPowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Power Saving 的本地化字符串。
        /// </summary>
        internal static string ChoiceMediumPowerSaving {
            get {
                return ResourceManager.GetString("ChoiceMediumPowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moderate Power Saving 的本地化字符串。
        /// </summary>
        internal static string ChoiceModeratePowerSaving {
            get {
                return ResourceManager.GetString("ChoiceModeratePowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never 的本地化字符串。
        /// </summary>
        internal static string ChoiceNever {
            get {
                return ResourceManager.GetString("ChoiceNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string ChoiceNone {
            get {
                return ResourceManager.GetString("ChoiceNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent Idle 的本地化字符串。
        /// </summary>
        internal static string ChoicePreventIdle {
            get {
                return ResourceManager.GetString("ChoicePreventIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Away Mode 的本地化字符串。
        /// </summary>
        internal static string ChoiceUseAwayMode {
            get {
                return ResourceManager.GetString("ChoiceUseAwayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot delete default or active power schemes. 的本地化字符串。
        /// </summary>
        internal static string DeleteSchemeMessage {
            get {
                return ResourceManager.GetString("DeleteSchemeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not valid. 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidGuid {
            get {
                return ResourceManager.GetString("ErrorInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must supply &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ErrorSpecifyAgrument {
            get {
                return ResourceManager.GetString("ErrorSpecifyAgrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must supply &apos;{0}&apos; and &apos;{1}&apos;.  的本地化字符串。
        /// </summary>
        internal static string ErrorSpecifyBothArguments {
            get {
                return ResourceManager.GetString("ErrorSpecifyBothArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument secondsTimer&apos;s value can not be greater than or equal to 315360000 seconds. 的本地化字符串。
        /// </summary>
        internal static string MaximumRebootTimerValue {
            get {
                return ResourceManager.GetString("MaximumRebootTimerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument secondsTimer&apos;s value can not be greater than or equal to 315360000 seconds. 的本地化字符串。
        /// </summary>
        internal static string MaximumShutdownTimerValue {
            get {
                return ResourceManager.GetString("MaximumShutdownTimerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The computer does not support hibernation (power state S4). 的本地化字符串。
        /// </summary>
        internal static string NoHibernationSupport {
            get {
                return ResourceManager.GetString("NoHibernationSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User does not have sufficient privileges to shutdown. 的本地化字符串。
        /// </summary>
        internal static string NoShutdownPrivilege {
            get {
                return ResourceManager.GetString("NoShutdownPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (AC-specific) 的本地化字符串。
        /// </summary>
        internal static string PostfixAcSpecific {
            get {
                return ResourceManager.GetString("PostfixAcSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (DC-specific) 的本地化字符串。
        /// </summary>
        internal static string PostfixDcSpecific {
            get {
                return ResourceManager.GetString("PostfixDcSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        internal static string PostfixPercentage {
            get {
                return ResourceManager.GetString("PostfixPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  seconds 的本地化字符串。
        /// </summary>
        internal static string PostfixSeconds {
            get {
                return ResourceManager.GetString("PostfixSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balanced 的本地化字符串。
        /// </summary>
        internal static string PowerSchemeBalancedTitle {
            get {
                return ResourceManager.GetString("PowerSchemeBalancedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High performance 的本地化字符串。
        /// </summary>
        internal static string PowerSchemeHighPerformanceTitle {
            get {
                return ResourceManager.GetString("PowerSchemeHighPerformanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified power scheme not found. 的本地化字符串。
        /// </summary>
        internal static string PowerSchemeNotFound {
            get {
                return ResourceManager.GetString("PowerSchemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power saver 的本地化字符串。
        /// </summary>
        internal static string PowerSchemePowerSaverTitle {
            get {
                return ResourceManager.GetString("PowerSchemePowerSaverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length of argument shutdownMessage cannot be greater than 511 characters. 的本地化字符串。
        /// </summary>
        internal static string RebootMessageLength {
            get {
                return ResourceManager.GetString("RebootMessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$ 的本地化字符串。
        /// </summary>
        internal static string RegularExpressionGuid {
            get {
                return ResourceManager.GetString("RegularExpressionGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length of argument shutdownMessage cannot be greater than 511 characters. 的本地化字符串。
        /// </summary>
        internal static string ShutdownMessageLength {
            get {
                return ResourceManager.GetString("ShutdownMessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e73a048d-bf27-4f12-9731-8b2076e8891f 的本地化字符串。
        /// </summary>
        internal static string SubgroupBatteryGuid {
            get {
                return ResourceManager.GetString("SubgroupBatteryGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0012ee47-9041-4b5d-9b77-535fba8b1442 的本地化字符串。
        /// </summary>
        internal static string SubgroupDiskGuid {
            get {
                return ResourceManager.GetString("SubgroupDiskGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7516b95f-f776-4464-8c53-06167f40cc99 的本地化字符串。
        /// </summary>
        internal static string SubgroupDisplayGuid {
            get {
                return ResourceManager.GetString("SubgroupDisplayGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9596fb26-9850-41fd-ac3e-f7c3c00afd4b 的本地化字符串。
        /// </summary>
        internal static string SubgroupMultimediaGuid {
            get {
                return ResourceManager.GetString("SubgroupMultimediaGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 501a4d13-42af-4429-9fd1-a8218c268e20 的本地化字符串。
        /// </summary>
        internal static string SubgroupPciExpressGuid {
            get {
                return ResourceManager.GetString("SubgroupPciExpressGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4f971e89-eebd-4455-a8de-9e59040e7347 的本地化字符串。
        /// </summary>
        internal static string SubgroupPowerButtonGuid {
            get {
                return ResourceManager.GetString("SubgroupPowerButtonGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 54533251-82be-4824-96c1-47b60b740d00 的本地化字符串。
        /// </summary>
        internal static string SubgroupProcessorGuid {
            get {
                return ResourceManager.GetString("SubgroupProcessorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 581a5406-53a3-4acd-af43-f685fa098e06 的本地化字符串。
        /// </summary>
        internal static string SubgroupSearchIndexingGuid {
            get {
                return ResourceManager.GetString("SubgroupSearchIndexingGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 238c9fa8-0aad-41ed-83f4-97be242c8f20 的本地化字符串。
        /// </summary>
        internal static string SubgroupSleepGuid {
            get {
                return ResourceManager.GetString("SubgroupSleepGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2a737441-1930-4402-8d77-b2bebba308a3 的本地化字符串。
        /// </summary>
        internal static string SubgroupUsbGuid {
            get {
                return ResourceManager.GetString("SubgroupUsbGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 19cbb8fa-5279-450e-9fac-8a3d5fedd0c1 的本地化字符串。
        /// </summary>
        internal static string SubgroupWirelessAdapterGuid {
            get {
                return ResourceManager.GetString("SubgroupWirelessAdapterGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows32 Error Code :  的本地化字符串。
        /// </summary>
        internal static string Win32ErrorCodeMessage {
            get {
                return ResourceManager.GetString("Win32ErrorCodeMessage", resourceCulture);
            }
        }
    }
}
